/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.25.1
// source: frontend_rpc/grpcdefs.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as frontend_rpc_grpcdefs_pb from '../frontend_rpc/grpcdefs_pb';


export class BackendClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorinfo = new grpcWeb.MethodDescriptor(
    '/Backend/info',
    grpcWeb.MethodType.UNARY,
    frontend_rpc_grpcdefs_pb.Void,
    frontend_rpc_grpcdefs_pb.Info,
    (request: frontend_rpc_grpcdefs_pb.Void) => {
      return request.serializeBinary();
    },
    frontend_rpc_grpcdefs_pb.Info.deserializeBinary
  );

  info(
    request: frontend_rpc_grpcdefs_pb.Void,
    metadata: grpcWeb.Metadata | null): Promise<frontend_rpc_grpcdefs_pb.Info>;

  info(
    request: frontend_rpc_grpcdefs_pb.Void,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: frontend_rpc_grpcdefs_pb.Info) => void): grpcWeb.ClientReadableStream<frontend_rpc_grpcdefs_pb.Info>;

  info(
    request: frontend_rpc_grpcdefs_pb.Void,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: frontend_rpc_grpcdefs_pb.Info) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Backend/info',
        request,
        metadata || {},
        this.methodDescriptorinfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Backend/info',
    request,
    metadata || {},
    this.methodDescriptorinfo);
  }

}

