class Io:
    DESK_ON_OFF = "deskonoff"
    DESK_OCCUPIED = "deskocc"
    DESK_HALT = "deskhlt"
    DESK_EMERGENCY_STOP = "deskemerg"
    DESK_EMERGENCY_STOP_STATION_MODE = "deskemergsb"
    DESK_SPEED_1 = "deskspd1"
    DESK_SPEED_2 = "deskspd2"
    DESK_SPEED_3 = "deskspd3"
    DESK_FORWARDS = "deskfw"
    DESK_BACKWARDS = "deskbw"
    DESK_PASSENGER_MODE = "deskpassenger"
    DESK_SERVICE_MODE = "deskser"
    DESK_CONFIRM_SYSTEM = "deskcnfsys"
    DESK_CONFIRM_OPERATION = "deskcnfop"
    DESK_START = "deskstart"
